"use server";

import { revalidatePath } from "next/cache";
import { requireContentManager } from "@/lib/auth/admin";
import { createClient } from "@/lib/supabase/server";
import type { AdminActionState } from "@/types/admin";

function value(data: FormData, name: string) { return String(data.get(name) ?? "").trim(); }
function nullable(data: FormData, name: string) { return value(data, name) || null; }
function lines(data: FormData, name: string) { const items = value(data, name).split(/\r?\n/).map((item) => item.trim()).filter(Boolean); return items.length ? items.slice(0, 30) : null; }

export async function saveSiteSettingsAction(_state: AdminActionState, data: FormData): Promise<AdminActionState> { await requireContentManager(); const mapsUrl = value(data, "mapsUrl"); const announcementUrl = value(data, "announcementUrl"); if (mapsUrl && !/^https:\/\//.test(mapsUrl)) return { status: "error", message: "رابط الخريطة يجب أن يبدأ بـ https://" }; if (announcementUrl && !announcementUrl.startsWith("/") && !/^https:\/\//.test(announcementUrl)) return { status: "error", message: "رابط الإعلان غير صالح." }; const socialLinks: Record<string, string> = {}; for (const key of ["instagram", "x", "facebook", "youtube", "snapchat"]) { const link = value(data, key); if (link) { try { if (new URL(link).protocol !== "https:") throw new Error(); socialLinks[key] = link; } catch { return { status: "error", message: `رابط ${key} غير صالح.` }; } } } const payload = { id: true, organization_name_ar: nullable(data, "organizationNameAr"), organization_name_en: nullable(data, "organizationNameEn"), about_ar: nullable(data, "aboutAr"), about_en: nullable(data, "aboutEn"), vision_ar: nullable(data, "visionAr"), vision_en: nullable(data, "visionEn"), mission_ar: nullable(data, "missionAr"), mission_en: nullable(data, "missionEn"), values_ar: lines(data, "valuesAr"), values_en: lines(data, "valuesEn"), phone: nullable(data, "phone"), whatsapp: nullable(data, "whatsapp"), email: nullable(data, "email"), address_ar: nullable(data, "addressAr"), address_en: nullable(data, "addressEn"), maps_url: mapsUrl || null, latitude: nullable(data, "latitude") ? Number(value(data, "latitude")) : null, longitude: nullable(data, "longitude") ? Number(value(data, "longitude")) : null, working_hours_ar: nullable(data, "workingHoursAr"), working_hours_en: nullable(data, "workingHoursEn"), social_links: socialLinks, default_seo_title_ar: nullable(data, "defaultSeoTitleAr"), default_seo_title_en: nullable(data, "defaultSeoTitleEn"), default_seo_description_ar: nullable(data, "defaultSeoDescriptionAr"), default_seo_description_en: nullable(data, "defaultSeoDescriptionEn"), medical_disclaimer_ar: nullable(data, "medicalDisclaimerAr"), medical_disclaimer_en: nullable(data, "medicalDisclaimerEn"), announcement_ar: nullable(data, "announcementAr"), announcement_en: nullable(data, "announcementEn"), announcement_url: announcementUrl || null, announcement_is_active: data.get("announcementIsActive") === "on" }; const supabase = await createClient(); const { error } = await supabase.from("site_settings").upsert(payload); if (error) return { status: "error", message: "تعذر حفظ الإعدادات." }; for (const path of ["/", "/about", "/contact", "/faq", "/articles"]) revalidatePath(path); revalidatePath("/admin/settings"); return { status: "success", message: "تم حفظ إعدادات المحتوى." }; }
