import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { contactDetails } from "@/data/contact";
import { getLocale, localized } from "@/lib/i18n";
import { getSiteSettings } from "@/lib/site-content";

export const metadata: Metadata = { title: "تواصل معنا | Contact" };

export default async function ContactPage() { const [settings, locale] = await Promise.all([getSiteSettings(), getLocale()]); const en = locale === "en"; const phone = settings?.phone || contactDetails.phone; const email = settings?.email || contactDetails.email; const address = settings ? localized(locale, settings.address_ar || contactDetails.location, settings.address_en) : contactDetails.location; const hours = settings && localized(locale, settings.working_hours_ar, settings.working_hours_en); return <Container className="py-section"><header className="max-w-3xl"><p className="text-sm font-bold text-brand">{en ? "Contact" : "تواصل معنا"}</p><h1 className="mt-4 text-4xl font-bold sm:text-5xl">{en ? "We are here to help" : "نحن هنا لمساعدتك"}</h1><p className="mt-5 text-base leading-8 text-muted">{en ? "Use the approved details below to contact the Dentally team." : "استخدم البيانات المعتمدة أدناه للتواصل مع فريق دينتالي."}</p></header><div className="mt-10 grid gap-5 md:grid-cols-2"><Card label={en ? "Phone" : "الهاتف"} value={phone} href={`tel:${phone}`} /><Card label={en ? "Email" : "البريد الإلكتروني"} value={email} href={`mailto:${email}`} /><Card label={en ? "Address" : "العنوان"} value={address} />{hours && <Card label={en ? "Working hours" : "ساعات العمل"} value={hours} />}</div>{settings?.maps_url && <a href={settings.maps_url} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex rounded-full bg-brand px-6 py-3 text-sm font-bold text-white">{en ? "Open map" : "فتح الخريطة"}</a>}</Container>; }
function Card({ label, value, href }: { label: string; value: string; href?: string }) { return <div className="rounded-card border border-line bg-surface p-7"><p className="text-xs font-bold text-muted">{label}</p>{href ? <a href={href} dir="ltr" className="mt-5 block text-lg font-bold text-brand">{value}</a> : <p className="mt-5 whitespace-pre-line text-lg font-bold leading-8">{value}</p>}</div>; }
