import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { getLocale, localized } from "@/lib/i18n";
import { getSiteSettings } from "@/lib/site-content";

export async function generateMetadata(): Promise<Metadata> { return { title: (await getLocale()) === "en" ? "About Dentally" : "عن دينتالي" }; }

export default async function AboutPage() { const [settings, locale] = await Promise.all([getSiteSettings(), getLocale()]); const en = locale === "en"; const about = settings && localized(locale, settings.about_ar, settings.about_en); const vision = settings && localized(locale, settings.vision_ar, settings.vision_en); const mission = settings && localized(locale, settings.mission_ar, settings.mission_en); const values = settings && localized(locale, settings.values_ar ?? [], settings.values_en); const hasContent=Boolean(about||vision||mission||(values&&values.length)); return <Container className="py-section"><header className="max-w-3xl"><p className="text-sm font-bold text-brand">{en ? "About Dentally" : "عن دينتالي"}</p><h1 className="mt-4 text-4xl font-bold sm:text-5xl">{settings ? localized(locale, settings.organization_name_ar || "مجمع دينتالي لطب الأسنان", settings.organization_name_en) : (en ? "Dentally Dental Complex" : "مجمع دينتالي لطب الأسنان")}</h1>{about && <p className="mt-6 whitespace-pre-line text-base leading-9 text-muted">{about}</p>}</header>{hasContent ? <div className="mt-12 grid gap-6 md:grid-cols-2">{vision && <Section title={en ? "Vision" : "الرؤية"} text={vision} />}{mission && <Section title={en ? "Mission" : "الرسالة"} text={mission} />}{values && values.length > 0 && <section className="rounded-card border border-line bg-surface p-7 md:col-span-2"><h2 className="text-2xl font-bold">{en ? "Values" : "القيم"}</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{values.map((value) => <li key={value} className="rounded-2xl bg-surface-muted p-4 text-sm leading-7">{value}</li>)}</ul></section>}</div> : <div className="mt-12 rounded-card border border-dashed border-line bg-surface p-10 text-center text-sm text-muted">{en ? "No approved clinic profile is currently available." : "لا تتوفر نبذة معتمدة عن المنشأة حاليًا."}</div>}</Container>; }
function Section({ title, text }: { title: string; text: string }) { return <section className="rounded-card border border-line bg-surface p-7"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-4 whitespace-pre-line text-sm leading-8 text-muted">{text}</p></section>; }
