import { AdminPageHeader } from "@/components/admin/page-header";
import { requireContentManager } from "@/lib/auth/admin";
import { getLocale } from "@/lib/i18n";
import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/types/database";

type Audit=Database["public"]["Tables"]["audit_logs"]["Row"];
const labels:Record<Audit["action"],string>={create:"إنشاء",update:"تحديث",publish:"نشر",hide:"إخفاء",soft_delete:"حذف منطقي",restore:"استعادة"};
type PageProps<Route extends string>={searchParams:Promise<Record<string,string|string[]|undefined>>;__route?:Route};
export default async function AuditLogPage({searchParams}:PageProps<"/admin/audit-log">){await requireContentManager();const[params,locale]=await Promise.all([searchParams,getLocale()]);const page=Math.max(1,Number(typeof params.page==="string"?params.page:"1")||1);const supabase=await createClient();const{data,error,count}=await supabase.from("audit_logs").select("*",{count:"exact"}).order("created_at",{ascending:false}).range((page-1)*50,page*50-1);const items=(data??[]) as Audit[];return <><AdminPageHeader eyebrow="الأمان والمراجعة" title="سجل التدقيق" description="بيانات وصفية للعمليات الإدارية المهمة دون تخزين محتوى أو أسرار أو بيانات مرضى."/>{error?<p className="mt-7 rounded-2xl bg-red-50 p-4 text-sm text-red-800">تعذر تحميل السجل. راجع Migration المطلوبة.</p>:<div className="mt-8 overflow-x-auto rounded-card border border-line bg-surface"><table className="w-full min-w-[760px] text-start text-sm"><thead className="bg-surface-muted text-xs text-muted"><tr><th className="p-4 text-start">الوقت</th><th className="p-4 text-start">العملية</th><th className="p-4 text-start">النوع</th><th className="p-4 text-start">معرف السجل</th><th className="p-4 text-start">معرف المنفذ</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-line"><td className="p-4" dir="ltr">{new Intl.DateTimeFormat(locale==="ar"?"ar-SA":"en-GB",{calendar:"gregory",dateStyle:"short",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(new Date(item.created_at))}</td><td className="p-4 font-bold">{labels[item.action]}</td><td className="p-4">{item.entity_type}</td><td className="p-4 font-mono text-xs">{item.entity_id}</td><td className="p-4 font-mono text-xs">{item.actor_user_id??"system"}</td></tr>)}</tbody></table>{!items.length&&<p className="p-8 text-center text-sm text-muted">لا توجد عمليات مسجلة بعد.</p>}</div>}<p className="mt-4 text-xs text-muted">الصفحة {page} — إجمالي السجلات: {count??0}</p></>}
