"use client";

import { useActionState, useEffect, useState } from "react";
import { saveGalleryAction, saveInsuranceAction, saveOfferAction, saveTestimonialAction, toggleCollectionDeletionAction } from "@/app/admin/collections/actions";
import { getSiteContentImageUrl, siteContentImageMaximumBytes, siteContentImageMimeTypes } from "@/lib/site-content-images";
import { formatRiyadhDateTimeInput } from "@/lib/date";
import type { AdminActionState } from "@/types/admin";
import type { GalleryItemRow, InsuranceProviderRow, OfferRow, TestimonialRow } from "@/types/collections";

const initial: AdminActionState = { status: "idle", message: "" };
const input = "min-h-11 rounded-xl border border-line bg-background px-3 text-sm font-normal text-foreground outline-none focus:border-brand";
const area = `${input} min-h-24 resize-y py-3 leading-7`;
const panel = "grid gap-4 rounded-card border border-line bg-surface p-5 sm:p-6";

export function InsuranceForm({ row }: { row?: InsuranceProviderRow }) { const [state, action, pending] = useActionState(saveInsuranceAction, initial); return <form action={action} className={panel}>{row && <input type="hidden" name="id" value={row.id} />}<Grid><Field label="اسم الشركة"><input className={input} name="nameAr" required minLength={2} maxLength={160} defaultValue={row?.name_ar ?? ""} /></Field><Field label="English name"><input className={input} name="nameEn" dir="ltr" maxLength={160} defaultValue={row?.name_en ?? ""} /></Field><Field label="الموقع الرسمي"><input className={input} name="websiteUrl" type="url" dir="ltr" defaultValue={row?.website_url ?? ""} /></Field><Order row={row} /></Grid><ImageField path={row?.image_path} /><Grid><Field label="وصف الشعار"><input className={input} name="imageAltAr" maxLength={180} defaultValue={row?.image_alt_ar ?? ""} /></Field><Field label="Logo alt text"><input className={input} name="imageAltEn" dir="ltr" maxLength={180} defaultValue={row?.image_alt_en ?? ""} /></Field></Grid><Published row={row} /><Result state={state} /><Save pending={pending} existing={Boolean(row)} /></form>; }

export function OfferForm({ row }: { row?: OfferRow }) { const [state, action, pending] = useActionState(saveOfferAction, initial); return <form action={action} className={panel}>{row && <input type="hidden" name="id" value={row.id} />}<Grid><Field label="العنوان"><input className={input} name="titleAr" required maxLength={180} defaultValue={row?.title_ar ?? ""} /></Field><Field label="English title"><input className={input} name="titleEn" dir="ltr" maxLength={180} defaultValue={row?.title_en ?? ""} /></Field><Field label="الوصف"><textarea className={area} name="descriptionAr" required maxLength={2000} defaultValue={row?.description_ar ?? ""} /></Field><Field label="English description"><textarea className={area} name="descriptionEn" dir="ltr" maxLength={2000} defaultValue={row?.description_en ?? ""} /></Field></Grid><ImageField path={row?.image_path} /><Grid><Field label="CTA بالعربية"><input className={input} name="ctaLabelAr" maxLength={80} defaultValue={row?.cta_label_ar ?? ""} /></Field><Field label="English CTA"><input className={input} name="ctaLabelEn" dir="ltr" maxLength={80} defaultValue={row?.cta_label_en ?? ""} /></Field><Field label="رابط CTA"><input className={input} name="ctaUrl" dir="ltr" defaultValue={row?.cta_url ?? ""} /></Field><Order row={row} /><Field label="بداية العرض"><input className={input} type="datetime-local" name="startAt" defaultValue={localDate(row?.start_at)} /></Field><Field label="نهاية العرض"><input className={input} type="datetime-local" name="endAt" defaultValue={localDate(row?.end_at)} /></Field><Field label="وصف الصورة"><input className={input} name="imageAltAr" maxLength={180} defaultValue={row?.image_alt_ar ?? ""} /></Field><Field label="Image alt"><input className={input} name="imageAltEn" dir="ltr" maxLength={180} defaultValue={row?.image_alt_en ?? ""} /></Field></Grid><Published row={row} /><Result state={state} /><Save pending={pending} existing={Boolean(row)} /></form>; }

export function TestimonialForm({ row }: { row?: TestimonialRow }) { const [state, action, pending] = useActionState(saveTestimonialAction, initial); return <form action={action} className={panel}>{row && <input type="hidden" name="id" value={row.id} />}<Grid><Field label="اسم العرض الموثق"><input className={input} name="displayName" maxLength={120} defaultValue={row?.display_name ?? ""} /></Field><Field label="أو تسمية مجهولة"><input className={input} name="anonymousLabelAr" maxLength={120} defaultValue={row?.anonymous_label_ar ?? ""} /></Field><Field label="Anonymous label"><input className={input} name="anonymousLabelEn" dir="ltr" maxLength={120} defaultValue={row?.anonymous_label_en ?? ""} /></Field><Field label="التقييم"><select className={input} name="rating" defaultValue={row?.rating ?? ""}><option value="">بدون تقييم</option>{[1,2,3,4,5].map((n)=><option key={n} value={n}>{n}</option>)}</select></Field><Field label="الرأي العربي"><textarea className={area} name="reviewAr" required minLength={10} maxLength={2000} defaultValue={row?.review_ar ?? ""} /></Field><Field label="English review"><textarea className={area} name="reviewEn" dir="ltr" minLength={10} maxLength={2000} defaultValue={row?.review_en ?? ""} /></Field><Field label="المصدر"><input className={input} name="source" maxLength={120} defaultValue={row?.source ?? ""} /></Field><Field label="رابط المصدر"><input className={input} name="sourceUrl" type="url" dir="ltr" defaultValue={row?.source_url ?? ""} /></Field><Order row={row} /></Grid><p className="text-xs leading-6 text-muted">لا تنشر إلا رأيًا حقيقيًا موثقًا ومصرحًا باستخدامه.</p><Published row={row} /><Result state={state} /><Save pending={pending} existing={Boolean(row)} /></form>; }

export function GalleryForm({ row }: { row?: GalleryItemRow }) { const [state, action, pending] = useActionState(saveGalleryAction, initial); return <form action={action} className={panel}>{row && <input type="hidden" name="id" value={row.id} />}<ImageField path={row?.image_path} required={!row} /><Grid><Field label="وصف الصورة"><input className={input} name="imageAltAr" required minLength={2} maxLength={180} defaultValue={row?.image_alt_ar ?? ""} /></Field><Field label="Image alt"><input className={input} name="imageAltEn" dir="ltr" maxLength={180} defaultValue={row?.image_alt_en ?? ""} /></Field><Field label="التعليق"><textarea className={area} name="captionAr" maxLength={500} defaultValue={row?.caption_ar ?? ""} /></Field><Field label="English caption"><textarea className={area} name="captionEn" dir="ltr" maxLength={500} defaultValue={row?.caption_en ?? ""} /></Field><Field label="التصنيف"><input className={input} name="category" maxLength={100} defaultValue={row?.category ?? ""} /></Field><Order row={row} /></Grid><p className="text-xs leading-6 text-muted">صور المنشأة فقط. صور المرضى وBefore/After غير مفعلة.</p><Published row={row} /><Result state={state} /><Save pending={pending} existing={Boolean(row)} /></form>; }

export function CollectionDeleteForm({ id, table, deleted }: { id: string; table: "insurance_providers"|"offers"|"testimonials"|"gallery_items"; deleted: boolean }) { const [state, action, pending] = useActionState(toggleCollectionDeletionAction, initial); return <form action={action} className="mt-2 flex flex-wrap items-center gap-3"><input type="hidden" name="id" value={id} /><input type="hidden" name="table" value={table} />{deleted && <input type="hidden" name="restore" value="yes" />}<button disabled={pending} className={`rounded-full px-4 py-2 text-xs font-bold ${deleted?"bg-brand text-white":"bg-red-50 text-red-800"}`}>{deleted?"استعادة مخفية":"حذف منطقي"}</button><Result state={state} /></form>; }

function ImageField({ path, required=false }: { path?: string|null; required?: boolean }) { const [preview,setPreview]=useState<string|null>(null);const [removeImage,setRemoveImage]=useState(false);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);const current=getSiteContentImageUrl(path??null);function changed(event:React.ChangeEvent<HTMLInputElement>){if(preview)URL.revokeObjectURL(preview);setPreview(null);const file=event.currentTarget.files?.[0];if(!file)return;if(!(siteContentImageMimeTypes as readonly string[]).includes(file.type)||file.size>siteContentImageMaximumBytes){event.currentTarget.value="";return}setRemoveImage(false);setPreview(URL.createObjectURL(file))}const shown=preview??(removeImage?null:current);return <div className="grid gap-4 md:grid-cols-[12rem_1fr]"><div className="aspect-[4/3] overflow-hidden rounded-2xl bg-brand-soft">{shown?(
  // Blob preview URLs are intentionally rendered with a native image element.
  // eslint-disable-next-line @next/next/no-img-element
  <img src={shown} alt="معاينة" className="h-full w-full object-contain" />
):<div className="grid h-full place-items-center text-xs text-muted">لا توجد صورة</div>}</div><div className="grid content-center gap-3"><Field label="الصورة — JPG/PNG/WebP حتى 5MB"><input className={`${input} py-2`} type="file" name="image" required={required} accept={siteContentImageMimeTypes.join(",")} onChange={changed} /></Field>{path&&<label className="flex gap-2 text-xs"><input type="checkbox" name="removeImage" value="yes" checked={removeImage} onChange={(e)=>setRemoveImage(e.target.checked)} /> إزالة الصورة الحالية</label>}</div></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-xs font-bold text-muted"><span>{label}</span>{children}</label>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 md:grid-cols-2">{children}</div>}
function Order({row}:{row?:{display_order:number}}){return <Field label="ترتيب العرض"><input className={input} name="displayOrder" type="number" min={0} defaultValue={row?.display_order??0} /></Field>}
function Published({row}:{row?:{is_active:boolean;deleted_at:string|null}}){return row&&!row.deleted_at?<label className="flex gap-3 text-sm font-semibold"><input type="checkbox" name="isActive" defaultChecked={row.is_active} /> منشور للعامة</label>:<p className="text-xs text-muted">السجل الجديد مخفي افتراضيًا.</p>}
function Result({state}:{state:AdminActionState}){return state.message?<p role={state.status==="error"?"alert":"status"} className={`text-xs ${state.status==="error"?"text-red-700":"text-emerald-700"}`}>{state.message}</p>:null}
function Save({pending,existing}:{pending:boolean;existing:boolean}){return <button disabled={pending} className="min-h-11 justify-self-end rounded-full bg-brand px-5 text-xs font-bold text-white">{pending?"جارٍ الحفظ...":existing?"حفظ":"إضافة مخفية"}</button>}
const localDate=formatRiyadhDateTimeInput;
