"use server";

import { revalidatePath } from "next/cache";
import { requireContentManager } from "@/lib/auth/admin";
import { createClient } from "@/lib/supabase/server";
import { siteContentImageMaximumBytes, siteContentImageMimeTypes, siteContentImagesBucket } from "@/lib/site-content-images";
import { isUuid } from "@/lib/validation/admin";
import type { AdminActionState } from "@/types/admin";
import { parseRiyadhDateTimeInput } from "@/lib/date";

type Table = "insurance_providers" | "offers" | "testimonials" | "gallery_items";
type ImageEntity = "insurance" | "offers" | "gallery";
type ImageData = { bytes: ArrayBuffer; type: "image/jpeg" | "image/png" | "image/webp"; extension: "jpg" | "png" | "webp" };
const failure = "تعذر تنفيذ العملية. تحقق من البيانات وMigration المطلوبة.";
const value = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const optional = (data: FormData, key: string) => value(data, key) || null;
const integer = (data: FormData, key: string) => Number(value(data, key));

function validOrder(order: number) { return Number.isSafeInteger(order) && order >= 0; }
function validHttps(url: string | null) { if (!url) return true; try { return new URL(url).protocol === "https:"; } catch { return false; } }
function validCta(url: string | null) { return !url || (/^\/[A-Za-z0-9/_?=&.-]*$/.test(url) || validHttps(url)); }
function match(bytes: Uint8Array, expected: number[], offset = 0) { return expected.every((item, index) => bytes[offset + index] === item); }

async function image(data: FormData): Promise<ImageData | null | "invalid"> { const file = data.get("image"); if (!(file instanceof File) || !file.size) return null; if (file.size > siteContentImageMaximumBytes || !(siteContentImageMimeTypes as readonly string[]).includes(file.type)) return "invalid"; const bytes = await file.arrayBuffer(); const signature = new Uint8Array(bytes.slice(0, 12)); const jpeg = file.type === "image/jpeg" && match(signature, [0xff,0xd8,0xff]); const png = file.type === "image/png" && match(signature, [0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]); const webp = file.type === "image/webp" && match(signature,[0x52,0x49,0x46,0x46]) && match(signature,[0x57,0x45,0x42,0x50],8); if (!jpeg && !png && !webp) return "invalid"; return { bytes, type: file.type as ImageData["type"], extension: jpeg ? "jpg" : png ? "png" : "webp" }; }
async function upload(supabase: Awaited<ReturnType<typeof createClient>>, entity: ImageEntity, id: string, file: ImageData) { const path = `${entity}/${id}/${crypto.randomUUID()}.${file.extension}`; const { error } = await supabase.storage.from(siteContentImagesBucket).upload(path, file.bytes, { contentType: file.type, cacheControl: "3600", upsert: false }); return error ? null : path; }
async function remove(supabase: Awaited<ReturnType<typeof createClient>>, path: string) { return (await supabase.storage.from(siteContentImagesBucket).remove([path])).error; }
function refresh(publicPath: string, adminPath: string) { revalidatePath("/"); revalidatePath(publicPath); revalidatePath(adminPath); }

async function saveWithImage(table: "insurance_providers" | "offers" | "gallery_items", entity: ImageEntity, data: FormData, payload: Record<string, unknown>, publicPath: string, adminPath: string): Promise<AdminActionState> { const submitted = await image(data); if (submitted === "invalid") return { status: "error", message: "الصورة يجب أن تكون JPG أو PNG أو WebP صالحة وبحد أقصى 5MB." }; const suppliedId = value(data,"id"); const id = suppliedId || crypto.randomUUID(); if (suppliedId && !isUuid(suppliedId)) return { status:"error", message:failure }; const supabase = await createClient(); let currentPath: string | null = null; if (suppliedId) { const { data: current } = await supabase.from(table).select("image_path,deleted_at").eq("id",id).maybeSingle(); if (!current || current.deleted_at) return { status:"error", message:"السجل غير موجود أو محذوف." }; currentPath = current.image_path; } const uploaded = submitted ? await upload(supabase,entity,id,submitted) : null; if (submitted && !uploaded) return { status:"error",message:"تعذر رفع الصورة." }; const nextPath = uploaded ?? (data.get("removeImage") === "yes" ? null : currentPath); if (table === "gallery_items" && !nextPath) { if (uploaded) await remove(supabase,uploaded); return {status:"error",message:"صورة المعرض مطلوبة."}; } const record = { ...payload, id, image_path: nextPath, ...(suppliedId ? {} : { is_active:false }) }; const result = suppliedId ? await supabase.from(table).update(record).eq("id",id) : await supabase.from(table).insert(record as never); if (result.error) { if(uploaded) await remove(supabase,uploaded); return {status:"error",message:failure}; } if(currentPath && currentPath !== nextPath) await remove(supabase,currentPath); refresh(publicPath,adminPath); return {status:"success",message:suppliedId ? "تم حفظ السجل." : "أُضيف السجل مخفيًا."}; }

export async function saveInsuranceAction(_state: AdminActionState, data: FormData): Promise<AdminActionState> { await requireContentManager(); const nameAr=value(data,"nameAr"), nameEn=optional(data,"nameEn"), website=optional(data,"websiteUrl"), order=integer(data,"displayOrder"); if(nameAr.length<2||nameAr.length>160||(nameEn&&nameEn.length>160)||!validHttps(website)||!validOrder(order)) return {status:"error",message:"تحقق من بيانات شركة التأمين."}; return saveWithImage("insurance_providers","insurance",data,{name_ar:nameAr,name_en:nameEn,image_alt_ar:optional(data,"imageAltAr"),image_alt_en:optional(data,"imageAltEn"),website_url:website,display_order:order,is_active:data.get("isActive")==="on"},"/insurance","/admin/insurance"); }
export async function saveOfferAction(_state: AdminActionState, data: FormData): Promise<AdminActionState> { await requireContentManager(); const titleAr=value(data,"titleAr"),descriptionAr=value(data,"descriptionAr"),cta=optional(data,"ctaUrl"),order=integer(data,"displayOrder"),startInput=optional(data,"startAt"),endInput=optional(data,"endAt"),start=startInput?parseRiyadhDateTimeInput(startInput):null,end=endInput?parseRiyadhDateTimeInput(endInput):null; if(titleAr.length<2||descriptionAr.length<4||!validCta(cta)||!validOrder(order)||(startInput&&!start)||(endInput&&!end)||(start&&end&&end<=start)) return {status:"error",message:"تحقق من بيانات العرض وفترته."}; return saveWithImage("offers","offers",data,{title_ar:titleAr,title_en:optional(data,"titleEn"),description_ar:descriptionAr,description_en:optional(data,"descriptionEn"),image_alt_ar:optional(data,"imageAltAr"),image_alt_en:optional(data,"imageAltEn"),cta_label_ar:optional(data,"ctaLabelAr"),cta_label_en:optional(data,"ctaLabelEn"),cta_url:cta,start_at:start,end_at:end,display_order:order,is_active:data.get("isActive")==="on"},"/offers","/admin/offers"); }
export async function saveGalleryAction(_state: AdminActionState, data: FormData): Promise<AdminActionState> { await requireContentManager(); const alt=value(data,"imageAltAr"),order=integer(data,"displayOrder"); if(alt.length<2||alt.length>180||!validOrder(order)) return {status:"error",message:"الوصف العربي للصورة مطلوب."}; return saveWithImage("gallery_items","gallery",data,{image_alt_ar:alt,image_alt_en:optional(data,"imageAltEn"),caption_ar:optional(data,"captionAr"),caption_en:optional(data,"captionEn"),category:optional(data,"category"),display_order:order,is_active:data.get("isActive")==="on"},"/gallery","/admin/gallery"); }
export async function saveTestimonialAction(_state: AdminActionState,data:FormData):Promise<AdminActionState>{await requireContentManager();const id=value(data,"id"),review=value(data,"reviewAr"),name=optional(data,"displayName"),anonymous=optional(data,"anonymousLabelAr"),rating=optional(data,"rating")?Number(value(data,"rating")):null,sourceUrl=optional(data,"sourceUrl"),order=integer(data,"displayOrder");if((id&&!isUuid(id))||review.length<10||(!name&&!anonymous)||(rating!==null&&(!Number.isInteger(rating)||rating<1||rating>5))||!validHttps(sourceUrl)||!validOrder(order))return{status:"error",message:"تحقق من بيانات الرأي ومصدره."};const payload={display_name:name,anonymous_label_ar:anonymous,anonymous_label_en:optional(data,"anonymousLabelEn"),review_ar:review,review_en:optional(data,"reviewEn"),rating,source:optional(data,"source"),source_url:sourceUrl,display_order:order,is_active:id?data.get("isActive")==="on":false};const supabase=await createClient();const result=id?await supabase.from("testimonials").update(payload).eq("id",id):await supabase.from("testimonials").insert(payload);if(result.error)return{status:"error",message:failure};refresh("/","/admin/testimonials");return{status:"success",message:id?"تم حفظ الرأي.":"أُضيف الرأي مخفيًا."};}
export async function toggleCollectionDeletionAction(_state:AdminActionState,data:FormData):Promise<AdminActionState>{await requireContentManager();const id=value(data,"id"),table=value(data,"table") as Table;if(!isUuid(id)||!["insurance_providers","offers","testimonials","gallery_items"].includes(table))return{status:"error",message:failure};const restore=data.get("restore")==="yes";const supabase=await createClient();const{error}=await supabase.from(table).update({deleted_at:restore?null:new Date().toISOString(),is_active:false}).eq("id",id);if(error)return{status:"error",message:failure};const paths:{[K in Table]:[string,string]}={insurance_providers:["/insurance","/admin/insurance"],offers:["/offers","/admin/offers"],testimonials:["/","/admin/testimonials"],gallery_items:["/gallery","/admin/gallery"]};refresh(...paths[table]);return{status:"success",message:restore?"استُعيد السجل مخفيًا.":"نُقل السجل إلى المحذوفات."};}
