"use server";

import { revalidatePath } from "next/cache";
import { requireContentManager } from "@/lib/auth/admin";
import { createClient } from "@/lib/supabase/server";
import { isUuid } from "@/lib/validation/admin";
import type { AdminActionState } from "@/types/admin";

function value(data: FormData, name: string) { return String(data.get(name) ?? "").trim(); }
export async function saveFaqAction(_state: AdminActionState, data: FormData): Promise<AdminActionState> { await requireContentManager(); const id = value(data, "id"); const questionAr = value(data, "questionAr"); const questionEn = value(data, "questionEn"); const answerAr = value(data, "answerAr"); const answerEn = value(data, "answerEn"); const order = Number(value(data, "displayOrder")); if ((id && !isUuid(id)) || questionAr.length < 4 || questionAr.length > 300 || answerAr.length < 4 || answerAr.length > 3000 || (questionEn && questionEn.length > 300) || (answerEn && answerEn.length > 3000) || !Number.isSafeInteger(order) || order < 0) return { status: "error", message: "تحقق من بيانات السؤال." }; const payload = { question_ar: questionAr, question_en: questionEn || null, answer_ar: answerAr, answer_en: answerEn || null, category: value(data, "category") || null, service_id: value(data, "serviceId") || null, display_order: order, is_active: id ? data.get("isActive") === "on" : false }; const supabase = await createClient(); const result = id ? await supabase.from("faq_items").update(payload).eq("id", id) : await supabase.from("faq_items").insert(payload); if (result.error) return { status: "error", message: "تعذر حفظ السؤال." }; revalidatePath("/faq"); revalidatePath("/admin/faq"); return { status: "success", message: id ? "تم تحديث السؤال." : "أُضيف السؤال مخفيًا." }; }
export async function toggleFaqDeletionAction(_state: AdminActionState, data: FormData): Promise<AdminActionState> { await requireContentManager(); const id = value(data, "id"); if (!isUuid(id)) return { status: "error", message: "معرف غير صالح." }; const restore = data.get("restore") === "yes"; const supabase = await createClient(); const { error } = await supabase.from("faq_items").update({ deleted_at: restore ? null : new Date().toISOString(), is_active: false }).eq("id", id); if (error) return { status: "error", message: "تعذر تنفيذ العملية." }; revalidatePath("/faq"); revalidatePath("/admin/faq"); return { status: "success", message: restore ? "استُعيد السؤال مخفيًا." : "نُقل السؤال إلى المحذوفات." }; }
